import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import web7 from "../public/web7.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Stephan Magnin Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Mon Portfolio</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="text-2xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://www.linkedin.com/in/stephanmagnin/"
                  target="_blank"
                >
                  Linkedin
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Stéphan Magnin
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Développeur d'application - Frontend
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              "Si vous pouvez rêver , vous pouvez le faire" Walt Disney
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <Image src={web7} width={100} height={100} />
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Mes atouts</h3>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                UX / IU Design
              </h3>
              <h4 className="text-gray-800 py-1">Figma</h4>
              <p className="text-gray-800 py-1">Adobe XD</p>
              <p className="text-gray-800 py-1">Responsive design</p>
              <p className="text-gray-800 py-1">Modélisation UML</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Programmation</h3>
              <h4 className="text-gray-800 py-1">HTML</h4>
              <p className="text-gray-800 py-1">CSS</p>
              <p className="text-gray-800 py-1">Javascript</p>
              <p className="text-gray-800 py-1">Divers CMS</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Gestion de projet
              </h3>
              <h4 className="text-gray-800 py-1">Clickup</h4>
              <p className="text-gray-800 py-1">Jira</p>
              <p className="text-gray-800 py-1">Odoo</p>
              <p className="text-gray-800 py-1">Trello</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Mes projets</h3>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 cursor-pointer ">
              <a
                href="https://stephanmagnin.github.io/Jeu-de-plateau-tour-par-tour/jeu.html"
                target="_blank"
              >
                <Image
                  className="rounded-lg object-cover cursor-pointer"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web1}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1 cursor-pointer">
              <a
                href="https://stephanmagnin.github.io/You-need-some-rest/"
                target="_blank"
              >
                <Image
                  className="rounded-lg object-cover cursor-pointer"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web2}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1 cursor-pointer">
              <a
                href="https://stephanmagnin.github.io/Generateur-de-citations/"
                target="_blank"
              >
                <Image
                  className="rounded-lg object-cover cursor-pointer"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web3}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1 cursor-pointer">
              <a
                href="https://stephanmagnin.github.io/Quiz-JavaScript/"
                target="_blank"
              >
                <Image
                  className="rounded-lg object-cover cursor-pointer"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web4}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1 cursor-pointer">
              <a
                href="https://stephanmagnin.github.io/Login-product/"
                target="_blank"
              >
                <Image
                  className="rounded-lg object-cover cursor-pointer"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web5}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1 cursor-pointer">
              <a
                href="https://stephanmagnin.github.io/Tic-Tac-Toe/"
                target="_blank"
              >
                <Image
                  className="rounded-lg object-cover cursor-pointer"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web6}
                />
              </a>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
